services:

  postgres:	
    image: postgres:16
    container_name: BooksKeeper-Db-Container
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - BooksKeeper-Db-Data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: BooksKeeperDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 554034
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:7-alpine
    container_name: BooksKeeper-Redis-Container
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  BooksKeeper-Db-Data:
  redis-data:  